name: Restrat Bokun Services
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
              systemctl stop BokunTicketSender.service
              systemctl start BokunTicketSender.service
              systemctl stop BokunPaymentLink.service
              systemctl start BokunPaymentLink.service
              ystemctl stop BokunPaymentChecker.service
              ystemctl start BokunPaymentChecker.service
